//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.NiFiSample
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Car.
    /// </summary>
    // *** Start programmer edit section *** (Car CustomAttributes)

    // *** End programmer edit section *** (Car CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "CarNumber as \'Car number\'",
            "CarBody as \'Car body\'",
            "CarDate as \'Car date\'",
            "CreateTime as \'Create time\'",
            "Creator as \'Creator\'",
            "EditTime as \'Edit time\'",
            "Editor as \'Editor\'"})]
    [View("CarE", new string[] {
            "CarNumber as \'Car number\'",
            "CarBody as \'Car body\'",
            "CarDate as \'Car date\'",
            "Brand as \'Brand\'",
            "Brand.Name as \'Name\'"}, Hidden = new string[] {
            "Brand.Name"})]
    [AssociatedDetailViewAttribute("CarE", "SparePart", "SparePartE", true, "", "Spare part", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("CarE", "Brand", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CarL", new string[] {
            "CarNumber as \'Car number\'",
            "CarBody as \'Car body\'",
            "CarDate as \'Car date\'",
            "Brand.Name as \'Name\'",
             "CreateTime",
            "Creator",
            "EditTime",
            "Editor"})]
    public class Car : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {

        private string fCarNumber;

        private IIS.NiFiSample.CarType fCarBody;

        private System.DateTime fCarDate;

        private IIS.NiFiSample.Brand fBrand;

        private IIS.NiFiSample.DetailArrayOfSparePart fSparePart;

        private System.Nullable<System.DateTime> fCreateTime;

        private string fCreator;

        private System.Nullable<System.DateTime> fEditTime;

        private string fEditor;

        // *** Start programmer edit section *** (Car CustomMembers)

        // *** End programmer edit section *** (Car CustomMembers)


        /// <summary>
        /// CarNumber.
        /// </summary>
        // *** Start programmer edit section *** (Car.CarNumber CustomAttributes)

        // *** End programmer edit section *** (Car.CarNumber CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string CarNumber
        {
            get
            {
                // *** Start programmer edit section *** (Car.CarNumber Get start)

                // *** End programmer edit section *** (Car.CarNumber Get start)
                string result = this.fCarNumber;
                // *** Start programmer edit section *** (Car.CarNumber Get end)

                // *** End programmer edit section *** (Car.CarNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.CarNumber Set start)

                // *** End programmer edit section *** (Car.CarNumber Set start)
                this.fCarNumber = value;
                // *** Start programmer edit section *** (Car.CarNumber Set end)

                // *** End programmer edit section *** (Car.CarNumber Set end)
            }
        }

        /// <summary>
        /// CarBody.
        /// </summary>
        // *** Start programmer edit section *** (Car.CarBody CustomAttributes)

        // *** End programmer edit section *** (Car.CarBody CustomAttributes)
        public virtual IIS.NiFiSample.CarType CarBody
        {
            get
            {
                // *** Start programmer edit section *** (Car.CarBody Get start)

                // *** End programmer edit section *** (Car.CarBody Get start)
                IIS.NiFiSample.CarType result = this.fCarBody;
                // *** Start programmer edit section *** (Car.CarBody Get end)

                // *** End programmer edit section *** (Car.CarBody Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.CarBody Set start)

                // *** End programmer edit section *** (Car.CarBody Set start)
                this.fCarBody = value;
                // *** Start programmer edit section *** (Car.CarBody Set end)

                // *** End programmer edit section *** (Car.CarBody Set end)
            }
        }

        /// <summary>
        /// CarDate.
        /// </summary>
        // *** Start programmer edit section *** (Car.CarDate CustomAttributes)

        // *** End programmer edit section *** (Car.CarDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime CarDate
        {
            get
            {
                // *** Start programmer edit section *** (Car.CarDate Get start)

                // *** End programmer edit section *** (Car.CarDate Get start)
                System.DateTime result = this.fCarDate;
                // *** Start programmer edit section *** (Car.CarDate Get end)

                // *** End programmer edit section *** (Car.CarDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.CarDate Set start)

                // *** End programmer edit section *** (Car.CarDate Set start)
                this.fCarDate = value;
                // *** Start programmer edit section *** (Car.CarDate Set end)

                // *** End programmer edit section *** (Car.CarDate Set end)
            }
        }

        /// <summary>
        /// Car.
        /// </summary>
        // *** Start programmer edit section *** (Car.Brand CustomAttributes)

        // *** End programmer edit section *** (Car.Brand CustomAttributes)
        [NotNull()]
        public virtual IIS.NiFiSample.Brand Brand
        {
            get
            {
                // *** Start programmer edit section *** (Car.Brand Get start)

                // *** End programmer edit section *** (Car.Brand Get start)
                IIS.NiFiSample.Brand result = this.fBrand;
                // *** Start programmer edit section *** (Car.Brand Get end)

                // *** End programmer edit section *** (Car.Brand Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.Brand Set start)

                // *** End programmer edit section *** (Car.Brand Set start)
                this.fBrand = value;
                // *** Start programmer edit section *** (Car.Brand Set end)

                // *** End programmer edit section *** (Car.Brand Set end)
            }
        }

        /// <summary>
        /// Car.
        /// </summary>
        // *** Start programmer edit section *** (Car.SparePart CustomAttributes)

        // *** End programmer edit section *** (Car.SparePart CustomAttributes)
        public virtual IIS.NiFiSample.DetailArrayOfSparePart SparePart
        {
            get
            {
                // *** Start programmer edit section *** (Car.SparePart Get start)

                // *** End programmer edit section *** (Car.SparePart Get start)
                if ((this.fSparePart == null))
                {
                    this.fSparePart = new IIS.NiFiSample.DetailArrayOfSparePart(this);
                }
                IIS.NiFiSample.DetailArrayOfSparePart result = this.fSparePart;
                // *** Start programmer edit section *** (Car.SparePart Get end)

                // *** End programmer edit section *** (Car.SparePart Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.SparePart Set start)

                // *** End programmer edit section *** (Car.SparePart Set start)
                this.fSparePart = value;
                // *** Start programmer edit section *** (Car.SparePart Set end)

                // *** End programmer edit section *** (Car.SparePart Set end)
            }
        }

        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Class2.CreateTime Get start)

                // *** End programmer edit section *** (Class2.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Class2.CreateTime Get end)

                // *** End programmer edit section *** (Class2.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class2.CreateTime Set start)

                // *** End programmer edit section *** (Class2.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Class2.CreateTime Set end)

                // *** End programmer edit section *** (Class2.CreateTime Set end)
            }
        }

        /// <summary>
        /// Creator.
        /// </summary>
        // *** Start programmer edit section *** (Class2.Creator CustomAttributes)

        // *** End programmer edit section *** (Class2.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Class2.Creator Get start)

                // *** End programmer edit section *** (Class2.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Class2.Creator Get end)

                // *** End programmer edit section *** (Class2.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class2.Creator Set start)

                // *** End programmer edit section *** (Class2.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Class2.Creator Set end)

                // *** End programmer edit section *** (Class2.Creator Set end)
            }
        }

        /// <summary>
        /// EditTime.
        /// </summary>
        // *** Start programmer edit section *** (Class2.EditTime CustomAttributes)

        // *** End programmer edit section *** (Class2.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Class2.EditTime Get start)

                // *** End programmer edit section *** (Class2.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Class2.EditTime Get end)

                // *** End programmer edit section *** (Class2.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class2.EditTime Set start)

                // *** End programmer edit section *** (Class2.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Class2.EditTime Set end)

                // *** End programmer edit section *** (Class2.EditTime Set end)
            }
        }

        /// <summary>
        /// Editor.
        /// </summary>
        // *** Start programmer edit section *** (Class2.Editor CustomAttributes)

        // *** End programmer edit section *** (Class2.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Class2.Editor Get start)

                // *** End programmer edit section *** (Class2.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Class2.Editor Get end)

                // *** End programmer edit section *** (Class2.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class2.Editor Set start)

                // *** End programmer edit section *** (Class2.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Class2.Editor Set end)

                // *** End programmer edit section *** (Class2.Editor Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.NiFiSample.Car));
                }
            }

            /// <summary>
            /// "CarE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarE", typeof(IIS.NiFiSample.Car));
                }
            }

            /// <summary>
            /// "CarL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarL", typeof(IIS.NiFiSample.Car));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}