FROM apache/superset

COPY Superset/superset_config.py /app/pythonpath/superset_config.py

RUN \
  pip install --upgrade pip; \
  pip install clickhouse-connect; \
  superset fab create-admin \
      --username admin \
      --firstname Superset \
      --lastname Admin \
      --email admin@admin.com \
      --password c1ickh0u5e; \
  superset db upgrade; \
  superset init;
